export const planColumns = {
  // data_received_time: {
  //   index: 0,
  //   name: "Data received time",
  //   value: "data_received_time",
  //   fixed: true,
  //   width: 10,
  // },
  // order_number: {
  //   index: 1,
  //   name: "Order Number",
  //   value: "order_number",
  //   fixed: true,
  //   width: 6,
  // },
  // order_status: {
  //   index: 2,
  //   name: "Order Status",
  //   value: "order_status",
  //   fixed: true,
  //   width: 8,
  // },
  // order_type: {
  //   index: 3,
  //   name: "Order Type",
  //   value: "order_type",
  //   fixed: true,
  //   width: 6,
  // },
  // mrp_controller: {
  //   index: 4,
  //   name: "MRP Controller",
  //   value: "mrp_controller",
  //   fixed: true,
  //   width: 8,
  // },
  // work_center: {
  //   index: 5,
  //   name: "Work Center",
  //   value: "work_center",
  //   fixed: true,
  //   width: 7,
  // },
  plant: {
    index: 6,
    name: "Plant",
    value: "plant",
    width: 5,
  },
  scheduled_finish: {
    index: 7,
    name: "Scheduled finish",
    value: "scheduled_finish",
    width: 10,
  },
  scheduled_start: {
    index: 8,
    name: "Scheduled start",
    value: "scheduled_start",
    width: 10,
  },
  production_version: {
    index: 9,
    name: "Production Version",
    value: "production_version",
    width: 10,
  },
  header_material: {
    index: 10,
    name: "Header Material",
    value: "header_material",
    width: 8,
  },
  group: {
    index: 11,
    name: "Group",
    value: "group",
    width: 6,
  },
  total_order_quantity: {
    index: 12,
    name: "Total Order Quantity",
    value: "total_order_quantity",
    width: 10,
  },
  header_stock: {
    index: 13,
    name: "Header Stock",
    value: "header_stock",
    width: 6,
  },
  order_UoM: {
    index: 14,
    name: "Order UoM",
    value: "order_UoM",
    width: 6,
  },
  header_Sloc: {
    index: 15,
    name: "Header Sloc",
    value: "header_Sloc",
    width: 6,
  },
  item_number: {
    index: 16,
    name: "Item Number",
    value: "item_number",
    width: 6,
  },
  components: {
    index: 17,
    name: "Components",
    value: "components",
    width: 7,
  },
  issue_quantity: {
    index: 18,
    name: "Issue Quantity",
    value: "issue_quantity",
    width: 8,
  },
  comp_stock: {
    index: 19,
    name: "Comp. Stock",
    value: "comp_stock",
    width: 6,
  },
  comp_Uom: {
    index: 20,
    name: "Comp. Uom",
    value: "comp_Uom",
    width: 6,
  },
  comp_Sloc: {
    index: 21,
    name: "Comp. Sloc",
    value: "comp_Sloc",
    width: 6,
  },
  iot_order_processing_status: {
    index: 22,
    name: "Order Processing Status",
    value: "iot_order_processing_status",
    width: 11,
  },
};
