export const PRESS_SHOP_FILTERS = "PRESS_SHOP_FILTERS";
//
export const PRESSSHOP_DOWNLOAD_HISTORY = "PRESSSHOP_DOWNLOAD_HISTORY";
export const PRESSSHOP_DOWNLOAD_HISTORY_LOADING =
  "PRESSSHOP_DOWNLOAD_HISTORY_LOADING";
