export const PRESS_SHOP_SET_MASTER_FILES = "PRESS_SHOP_SET_MASTER_FILES";
export const PRESS_SHOP_ADD_MASTER_FILE = "PRESS_SHOP_ADD_MASTER_FILE";
export const PRESS_SHOP_SET_MASTER_LOADING = "PRESS_SHOP_SET_MASTER_LOADING";
export const PRESS_SHOP_SET_UPLOAD_MASTER_LOADING =
  "PRESS_SHOP_SET_UPLOAD_MASTER_LOADING";
export const PRESS_SHOP_SET_APPROVED = "PRESS_SHOP_SET_APPROVED";

export const PRESS_SHOP_ADD_MASTER_FILE_API_STATUS =
  "PRESS_SHOP_ADD_MASTER_FILE_API_STATUS";
