export const PRESS_SHOP_SET_PLAN_STATUS = "PRESS_SHOP_SET_PLAN_STATUS";
export const PRESS_SHOP_SET_PLAN_ALERTS = "PRESS_SHOP_SET_PLAN_ALERTS";
export const PRESS_SHOP_SET_PLAN_ALERTS_LOADING =
  "PRESS_SHOP_SET_PLAN_ALERTS_LOADING";
