export const PRESS_SHOP_QUALITY_REASONS = "PRESS_SHOP_QUALITY_REASONS";
export const PRESS_SHOP_QUALITY_TOTAL_REWORK =
  "PRESS_SHOP_QUALITY_TOTAL_REWORK";
export const PRESS_SHOP_QUALITY_PENDING_TOTAL_REWORK =
  "PRESS_SHOP_QUALITY_PENDING_TOTAL_REWORK";
