export const PRESS_SHOP_SET_SITES = "PRESS_SHOP_SET_SITES";
export const PRESS_SHOP_SET_SHOP = "PRESS_SHOP_SET_SHOP";
export const PRESS_SHOP_SET_SITE = "PRESS_SHOP_SET_SITE";
export const PRESS_SHOP_SET_LOCATION = "PRESS_SHOP_SET_LOCATION";
export const PRESS_SHOP_SET_PLANT = "PRESS_SHOP_SET_PLANT";
export const PRESS_SHOP_SET_LOADING = "PRESS_SHOP_SET_LOADING";
export const PRESS_SHOP_FILTERS_CHANGED = "PRESS_SHOP_FILTERS_CHANGED";
// export const PRESS_SHOP_REFRESHED = "PRESS_SHOP_REFRESHED";
