export const editModalColumn = {
  checkbox: {
    index: -1,
    name: "",
    value: "checkbox",
    width: 2.2,
    fixed: true,
  },
  plant: {
    index: 0,
    name: "Plant",
    value: "plant",
    width: 4,
    fixed: true,
  },
  shop: {
    index: 1,
    name: "Shop",
    value: "shop",
    width: 4,
    fixed: true,
  },
  header_material: {
    index: 2,
    name: "Header Material No.",
    value: "header_material",
    width: 9,
    fixed: true,
  },
  machine: {
    index: 3,
    name: "Machine",
    value: "machine",
    width: 6,
    fixed: true,
  },
  start_time: {
    index: 4,
    name: "Start Time",
    value: "start_time",
    width: 8,
  },
  output_part_number1: {
    index: 5,
    name: "Output Part Number 1",
    value: "output_part_number1",
    width: 10,
  },
  output_part_number2: {
    index: 6,
    name: "Output Part Number 2",
    value: "output_part_number2",
    width: 10,
  },
  output_part_number3: {
    index: 7,
    name: "Output Part Number 3",
    value: "output_part_number3",
    width: 10,
  },
  output_part_number4: {
    index: 8,
    name: "Output Part Number 4",
    value: "output_part_number4",
    width: 10,
  },
  ok_qty1: {
    index: 9,
    name: "OK Qty 1",
    value: "ok_qty1",
    width: 6,
  },
  ok_qty2: {
    index: 10,
    name: "OK Qty 2",
    value: "ok_qty2",
    width: 6,
  },
  ok_qty3: {
    index: 11,
    name: "OK Qty 3",
    value: "ok_qty3",
    width: 6,
  },
  ok_qty4: {
    index: 12,
    name: "OK Qty 4",
    value: "ok_qty4",
    width: 6,
  },
  input_part_number1: {
    index: 13,
    name: "Input Part Number 1",
    value: "input_part_number1",
    width: 10,
  },
  input_part_number2: {
    index: 14,
    name: "Input Part Number 2",
    value: "input_part_number2",
    width: 10,
  },
  input1_material_batch_details: {
    index: 14,
    name: "Input 1 Material Batch Details",
    value: "input1_material_batch_details",
    width: 12,
  },
  input2_material_batch_details: {
    index: 16,
    name: "Input 2 Material Batch Details",
    value: "input2_material_batch_details",
    width: 12,
  },
  prod_version: {
    index: 17,
    name: "Prod Version",
    value: "prod_version",
    width: 6,
  },
  error_message: {
    index: 18,
    name: "Error Message",
    value: "error_message",
    width: 8,
  },
  type_: {
    index: 19,
    name: "Type",
    value: "type_",
    width: 6,
  },
};
